---

# write package config

- import_tasks: ../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: 'package.accept_keywords'
        file: 'dev-lang-php'
        entries:
          - '>=dev-lang/php-7.0 ~amd64'
      - section: "package.mask"
        file: "dev-lang-php"
        entries:
          - ">=dev-lang/php-7.1"
    portage_packages: []


# install php 7.0

- name: install php 7.0
  become: yes
  portage: package=">=dev-lang/php-7.0" state="emerged" newuse=yes update=yes
  notify: php - restart
