---

# write package config

- import_tasks: ../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: 'package.accept_keywords'
        file: 'dev-lang-php'
        entries:
          - '>=dev-lang/php-7.2 ~amd64'
      - section: "package.mask"
        file: "dev-lang-php"
        entries:
          - ">=dev-lang/php-7.3"
      - section: "package.unmask"
        file: "dev-lang-php"
        entries:
          - ">=dev-lang/php-7.2.0_rc2"
    portage_packages: []


# install php 7.2

- name: install php 7.2
  become: yes
  portage: package=">=dev-lang/php-7.2" state="emerged" newuse=yes update=yes
  notify: php - restart
