---

# write package config

- include: ../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "dev-lang-php-apache2"
        entries:
          - ">=app-eselect/eselect-php-0.9.1 apache2"
    portage_packages: []
  when: "'apache2' in php_extensions_merged"

- include: ../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.mask"
        file: "dev-lang-php"
        entries:
          - ">=dev-lang/php-7.0"
    portage_packages: []


# install php 5.6

- name: install php 5.6
  become: yes
  portage: package=">=dev-lang/php-5.6" state="emerged" newuse=yes update=yes
  notify: php - restart
