---

# write package config

- include: ../../portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "dev-lang-php-apache2"
        entries:
          - ">=app-eselect/eselect-php-0.9.1 apache2"
    portage_packages: []
  when: "'apache2' in php_extensions_merged"

- include: ../../portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: 'package.accept_keywords'
        file: 'dev-lang-php'
        entries:
          - '>=dev-lang/php-7.0 ~amd64'
    portage_packages: []


# install php 7.0

- name: install php 7.0
  become: yes
  portage: package=">=dev-lang/php-7.0" state="emerged" newuse=yes update=yes
  notify: php - restart
