---

# set facts

- set_fact:
    php_extensions_merged: "{{ php_extensions_default|union(php_extensions) }}"
    php_config_merged: "{{ php_config_default | union(php_config) }}"


# write package config

- name: write used php extensions into package.use file
  become: yes
  template: src="package.use.j2" dest="/etc/portage/package.use/dev-lang-php-extensions"

- import_tasks: ../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "dev-lang-php-apache2"
        entries:
          - ">=app-eselect/eselect-php-0.9.2 apache2"
    portage_packages: []
  when: "'apache2' in php_extensions_merged"

- import_tasks: ../../vundb-portage/tasks/gentoo/main.yml
  vars:
    portage_configuration:
      - section: "package.use"
        file: "dev-lang-php-fpm"
        entries:
          - ">=app-eselect/eselect-php-0.9.2 fpm"
    portage_packages: []
  when: "'fpm' in php_extensions_merged"


# install version specific packages

- import_tasks: install-php56.yml
  when: php_version == "5.6"

- import_tasks: install-php70.yml
  when: php_version == "7.0"

- import_tasks: install-php71.yml
  when: php_version == "7.1"

- import_tasks: install-php72.yml
  when: php_version == "7.2"


# post installation tasks

- name: ensure php-fpm service is running (if requred)
  become: yes
  service: name=php-fpm state=started enabled=yes
  when: "'fpm' in php_extensions_merged"


# configure php

- import_tasks: configure-php.yml

# the tasks included in this playbook are moved to configure-php.yml
#- import_tasks: configure-php-fpm.yml
