---

# fail when distribution is not supported

- name: check if distribution is supported
  fail: msg="'{{ ansible_distribution }}' is not supported by this role"
  when: ansible_distribution not in ["Gentoo"]

- name: check if chosen version is supported
  fail: msg="PHP version '{{ php_version }}' is not supported by this role"
  when: php_version not in php_version_supported


# run os specific tasks

- import_tasks: gentoo/main.yml
  when: ansible_distribution == "Gentoo"
